-- ==============================================================================
-- Migration: Create coupons table for Sri Lakshmi Durga Agencies
-- Matches existing backend/models/Coupon.js Mongoose schema exactly
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.coupons (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  "discountType" text NOT NULL DEFAULT 'PERCENT' CHECK ("discountType" IN ('PERCENT', 'FLAT')),
  "discountValue" numeric(10, 2) NOT NULL,
  "minOrderAmount" numeric(10, 2) DEFAULT 0,
  "isActive" boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_coupons_code ON public.coupons (code);
CREATE INDEX IF NOT EXISTS idx_coupons_is_active ON public.coupons ("isActive");

-- Shared updated_at trigger helper
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_updated_at_coupons ON public.coupons;
CREATE TRIGGER set_updated_at_coupons
BEFORE UPDATE ON public.coupons
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

-- Enable Row Level Security (RLS)
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;

-- Backend Supabase service role access
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE public.coupons
TO service_role;

-- Allow backend inserts using the identity sequence
GRANT USAGE, SELECT
ON SEQUENCE public.coupons_id_seq
TO service_role;

-- Documentation
COMMENT ON TABLE public.coupons IS 'Store promotional coupons for Sri Lakshmi Durga Agencies';
COMMENT ON COLUMN public.coupons.code IS 'Unique coupon promo code (always uppercase)';
COMMENT ON COLUMN public.coupons."discountType" IS 'Discount calculation mode: PERCENT or FLAT';
COMMENT ON COLUMN public.coupons."discountValue" IS 'Percentage rate or flat amount in INR';
COMMENT ON COLUMN public.coupons."minOrderAmount" IS 'Minimum cart value required to apply coupon';
COMMENT ON COLUMN public.coupons."isActive" IS 'Coupon validity toggle';
