-- ==============================================================================
-- Migration: Create home_banners table for Sri Lakshmi Durga Agencies
-- Matches existing backend/models/HomeBanner.js Mongoose schema exactly
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.home_banners (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "smallText" text DEFAULT 'Welcome to Sri Lakshmi Durga Agencies',
  title text DEFAULT 'Elegant Ladies Clothing & Essentials',
  description text DEFAULT 'Shop beautiful kurtis, dresses, tops, essentials and accessories at affordable prices.',
  "offerText" text DEFAULT 'Up to 40% OFF',
  image text DEFAULT '',
  "isActive" boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);


-- Index for fast lookup of active banners
CREATE INDEX IF NOT EXISTS idx_home_banners_is_active ON public.home_banners ("isActive");
CREATE INDEX IF NOT EXISTS idx_home_banners_created_at ON public.home_banners (created_at DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE public.home_banners ENABLE ROW LEVEL SECURITY;

-- Allow storefront users to read banners
GRANT SELECT
ON TABLE public.home_banners
TO anon, authenticated;

-- Allow backend Supabase secret/service role to manage banners
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE public.home_banners
TO service_role;

-- Allow backend inserts using the identity sequence
GRANT USAGE, SELECT
ON SEQUENCE public.home_banners_id_seq
TO service_role;

DROP POLICY IF EXISTS "Allow public read access to active banners"
ON public.home_banners;

CREATE POLICY "Allow public read access to active banners"
ON public.home_banners
FOR SELECT
TO anon, authenticated
USING ("isActive" = true);

-- Documentation
COMMENT ON TABLE public.home_banners IS 'Hero banner configuration for Sri Lakshmi Durga Agencies homepage';
COMMENT ON COLUMN public.home_banners."smallText" IS 'Badge text shown above main headline (e.g. Welcome message)';
COMMENT ON COLUMN public.home_banners."offerText" IS 'Promotional offer badge text (e.g. Up to 40% OFF)';
COMMENT ON COLUMN public.home_banners."isActive" IS 'Banner visibility toggle';
