-- ==============================================================================
-- Migration: Create orders table for Sri Lakshmi Durga Agencies
-- Matches existing backend/models/Order.js Mongoose schema exactly
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderId" text NOT NULL UNIQUE,
  customer jsonb NOT NULL DEFAULT '{}'::jsonb,
  customer_email text,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  "totalAmount" numeric(10, 2) NOT NULL,
  "deliveryCharge" numeric(10, 2) DEFAULT 0,
  "discountAmount" numeric(10, 2) DEFAULT 0,
  "couponCode" text DEFAULT '',
  "finalAmount" numeric(10, 2) NOT NULL,
  "paymentMethod" text NOT NULL DEFAULT 'COD' CHECK ("paymentMethod" IN ('COD', 'ONLINE')),
  "paymentStatus" text NOT NULL DEFAULT 'Pending' CHECK (
    "paymentStatus" IN ('Pending', 'Paid', 'Failed', 'Cancelled', 'Refund Pending', 'Refunded')
  ),
  "razorpayOrderId" text DEFAULT '',
  "razorpayPaymentId" text DEFAULT '',
  "razorpaySignature" text DEFAULT '',
  "orderStatus" text NOT NULL DEFAULT 'Order Placed' CHECK (
    "orderStatus" IN (
      'Order Placed',
      'Confirmed',
      'Packed',
      'Shipped',
      'Out for Delivery',
      'Delivered',
      'Cancelled',
      'Returned'
    )
  ),
  "trackingId" text DEFAULT '',
  "stockRestored" boolean DEFAULT false,
  legacy_mongo_id text UNIQUE,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Indexes for performance and reporting
CREATE INDEX IF NOT EXISTS idx_orders_order_id ON public.orders ("orderId");
CREATE INDEX IF NOT EXISTS idx_orders_customer_email ON public.orders (customer_email);
CREATE INDEX IF NOT EXISTS idx_orders_order_status ON public.orders ("orderStatus");
CREATE INDEX IF NOT EXISTS idx_orders_payment_status ON public.orders ("paymentStatus");
CREATE INDEX IF NOT EXISTS idx_orders_payment_method ON public.orders ("paymentMethod");
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_legacy_mongo_id ON public.orders (legacy_mongo_id);

-- Updated_at trigger
DROP TRIGGER IF EXISTS set_updated_at_orders ON public.orders;
CREATE TRIGGER set_updated_at_orders
BEFORE UPDATE ON public.orders
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

-- Enable Row Level Security (RLS)
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Backend Supabase service role access (No anonymous direct browser access to customer orders)
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE public.orders
TO service_role;

-- Allow backend inserts using the identity sequence
GRANT USAGE, SELECT
ON SEQUENCE public.orders_id_seq
TO service_role;

-- Documentation
COMMENT ON TABLE public.orders IS 'Customer order records for Sri Lakshmi Durga Agencies';
COMMENT ON COLUMN public.orders."orderId" IS 'Human-readable unique order identifier (e.g. ORD1781070601445)';
COMMENT ON COLUMN public.orders.customer IS 'Customer snapshot {name, mobile, email, address, city, state, pincode}';
COMMENT ON COLUMN public.orders.items IS 'Historical snapshot array of order items [{productId, name, image, selectedSize, quantity, price}]';
COMMENT ON COLUMN public.orders."stockRestored" IS 'Safety flag ensuring inventory is only restocked once upon cancellation/return';
COMMENT ON COLUMN public.orders.legacy_mongo_id IS 'Previous MongoDB ObjectId string for backwards compatibility';
