-- ==============================================================================
-- Migration: Create products table for Sri Lakshmi Durga Agencies
-- Matches existing backend/models/Product.js Mongoose schema exactly
-- ==============================================================================

-- Drop existing dummy or conflicting table to guarantee exact schema alignment
DROP TABLE IF EXISTS public.products CASCADE;

CREATE TABLE public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  category text NOT NULL,
  price numeric(10, 2) NOT NULL,
  "oldPrice" numeric(10, 2) DEFAULT 0,
  sizes text[] DEFAULT '{}'::text[],
  colors text[] DEFAULT '{}'::text[],
  fabric text DEFAULT '',
  stock integer DEFAULT 0,
  image text NOT NULL,
  images text[] DEFAULT '{}'::text[],
  description text DEFAULT '',
  rating numeric(3, 2) DEFAULT 0,
  "numReviews" integer DEFAULT 0,
  reviews jsonb DEFAULT '[]'::jsonb,
  "isActive" boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Create index on category and isActive for fast public store filtering
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products (category);
CREATE INDEX IF NOT EXISTS idx_products_is_active ON public.products ("isActive");
CREATE INDEX IF NOT EXISTS idx_products_created_at ON public.products (created_at DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Drop policy if exists to allow idempotent execution
DROP POLICY IF EXISTS "Allow public read access" ON public.products;

-- Policy: Allow anonymous and authenticated public read access
CREATE POLICY "Allow public read access"
ON public.products
FOR SELECT
USING (true);

-- Documentation
COMMENT ON TABLE public.products IS 'Product catalog for Sri Lakshmi Durga Agencies';
COMMENT ON COLUMN public.products."oldPrice" IS 'Strikethrough / original MRP price';
COMMENT ON COLUMN public.products.reviews IS 'Array of review objects [{userName, userEmail, rating, comment, createdAt}]';
COMMENT ON COLUMN public.products."isActive" IS 'Soft deletion toggle: true = active in storefront, false = archived';
