-- ==============================================================================
-- SRI LAKSHMI DURGA AGENCIES: COMPLETE SUPABASE POSTGRESQL SCHEMA
-- Execute this entire file in your Supabase Dashboard -> SQL Editor
-- ==============================================================================

-- 1. PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  category text NOT NULL,
  price numeric(10, 2) NOT NULL,
  "oldPrice" numeric(10, 2) DEFAULT 0,
  sizes text[] DEFAULT '{}'::text[],
  colors text[] DEFAULT '{}'::text[],
  fabric text DEFAULT '',
  stock integer DEFAULT 0,
  image text NOT NULL,
  images text[] DEFAULT '{}'::text[],
  description text DEFAULT '',
  rating numeric(3, 2) DEFAULT 0,
  "numReviews" integer DEFAULT 0,
  reviews jsonb DEFAULT '[]'::jsonb,
  "isActive" boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_products_category ON public.products (category);
CREATE INDEX IF NOT EXISTS idx_products_is_active ON public.products ("isActive");
CREATE INDEX IF NOT EXISTS idx_products_created_at ON public.products (created_at DESC);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.products TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.products_id_seq TO service_role;
GRANT SELECT ON TABLE public.products TO anon, authenticated;

DROP POLICY IF EXISTS "Allow public read access" ON public.products;
CREATE POLICY "Allow public read access" ON public.products FOR SELECT USING (true);


-- 2. HOME BANNERS TABLE
CREATE TABLE IF NOT EXISTS public.home_banners (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "smallText" text DEFAULT 'Welcome to Sri Lakshmi Durga Agencies',
  title text DEFAULT 'Elegant Ladies Clothing & Essentials',
  description text DEFAULT 'Shop beautiful kurtis, dresses, tops, essentials and accessories at affordable prices.',
  "offerText" text DEFAULT 'Up to 40% OFF',
  image text DEFAULT '',
  "isActive" boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_home_banners_is_active ON public.home_banners ("isActive");
CREATE INDEX IF NOT EXISTS idx_home_banners_created_at ON public.home_banners (created_at DESC);

ALTER TABLE public.home_banners ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public.home_banners TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.home_banners TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.home_banners_id_seq TO service_role;

DROP POLICY IF EXISTS "Allow public read access to active banners" ON public.home_banners;
CREATE POLICY "Allow public read access to active banners"
ON public.home_banners FOR SELECT TO anon, authenticated USING ("isActive" = true);


-- 3. COUPONS TABLE
CREATE TABLE IF NOT EXISTS public.coupons (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  "discountType" text NOT NULL DEFAULT 'PERCENT' CHECK ("discountType" IN ('PERCENT', 'FLAT')),
  "discountValue" numeric(10, 2) NOT NULL,
  "minOrderAmount" numeric(10, 2) DEFAULT 0,
  "isActive" boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_coupons_code ON public.coupons (code);
CREATE INDEX IF NOT EXISTS idx_coupons_is_active ON public.coupons ("isActive");

ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.coupons TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.coupons_id_seq TO service_role;


-- 4. USERS TABLE
CREATE TABLE IF NOT EXISTS public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  password text NOT NULL,
  role text NOT NULL DEFAULT 'customer' CHECK (role IN ('customer', 'admin')),
  "resetOtp" text DEFAULT '',
  "resetOtpExpire" timestamptz,
  legacy_mongo_id text UNIQUE,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_users_email ON public.users (email);
CREATE INDEX IF NOT EXISTS idx_users_role ON public.users (role);
CREATE INDEX IF NOT EXISTS idx_users_legacy_mongo_id ON public.users (legacy_mongo_id);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.users TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.users_id_seq TO service_role;


-- 5. ORDERS TABLE
CREATE TABLE IF NOT EXISTS public.orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderId" text NOT NULL UNIQUE,
  customer jsonb NOT NULL DEFAULT '{}'::jsonb,
  customer_email text,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  "totalAmount" numeric(10, 2) NOT NULL,
  "deliveryCharge" numeric(10, 2) DEFAULT 0,
  "discountAmount" numeric(10, 2) DEFAULT 0,
  "couponCode" text DEFAULT '',
  "finalAmount" numeric(10, 2) NOT NULL,
  "paymentMethod" text NOT NULL DEFAULT 'COD' CHECK ("paymentMethod" IN ('COD', 'ONLINE')),
  "paymentStatus" text NOT NULL DEFAULT 'Pending' CHECK (
    "paymentStatus" IN ('Pending', 'Paid', 'Failed', 'Cancelled', 'Refund Pending', 'Refunded')
  ),
  "razorpayOrderId" text DEFAULT '',
  "razorpayPaymentId" text DEFAULT '',
  "razorpaySignature" text DEFAULT '',
  "orderStatus" text NOT NULL DEFAULT 'Order Placed' CHECK (
    "orderStatus" IN (
      'Order Placed',
      'Confirmed',
      'Packed',
      'Shipped',
      'Out for Delivery',
      'Delivered',
      'Cancelled',
      'Returned'
    )
  ),
  "trackingId" text DEFAULT '',
  "stockRestored" boolean DEFAULT false,
  legacy_mongo_id text UNIQUE,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_orders_order_id ON public.orders ("orderId");
CREATE INDEX IF NOT EXISTS idx_orders_customer_email ON public.orders (customer_email);
CREATE INDEX IF NOT EXISTS idx_orders_order_status ON public.orders ("orderStatus");
CREATE INDEX IF NOT EXISTS idx_orders_payment_status ON public.orders ("paymentStatus");
CREATE INDEX IF NOT EXISTS idx_orders_payment_method ON public.orders ("paymentMethod");
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_legacy_mongo_id ON public.orders (legacy_mongo_id);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.orders TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.orders_id_seq TO service_role;


-- 6. SHARED AUTO-UPDATE TIMESTAMP TRIGGER
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_updated_at_coupons ON public.coupons;
CREATE TRIGGER set_updated_at_coupons BEFORE UPDATE ON public.coupons FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_updated_at_users ON public.users;
CREATE TRIGGER set_updated_at_users BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_updated_at_orders ON public.orders;
CREATE TRIGGER set_updated_at_orders BEFORE UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
