-- ==============================================================================
-- Migration: Create users table for Sri Lakshmi Durga Agencies
-- Matches existing backend/models/User.js Mongoose schema exactly
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  password text NOT NULL,
  role text NOT NULL DEFAULT 'customer' CHECK (role IN ('customer', 'admin')),
  "resetOtp" text DEFAULT '',
  "resetOtpExpire" timestamptz,
  legacy_mongo_id text UNIQUE,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Indexes for fast lookup
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users (email);
CREATE INDEX IF NOT EXISTS idx_users_role ON public.users (role);
CREATE INDEX IF NOT EXISTS idx_users_legacy_mongo_id ON public.users (legacy_mongo_id);

-- Updated_at trigger
DROP TRIGGER IF EXISTS set_updated_at_users ON public.users;
CREATE TRIGGER set_updated_at_users
BEFORE UPDATE ON public.users
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

-- Enable Row Level Security (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Backend Supabase service role access (No public browser access to user credentials)
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE public.users
TO service_role;

-- Allow backend inserts using the identity sequence
GRANT USAGE, SELECT
ON SEQUENCE public.users_id_seq
TO service_role;

-- Documentation
COMMENT ON TABLE public.users IS 'Customer and Administrator accounts for Sri Lakshmi Durga Agencies';
COMMENT ON COLUMN public.users.email IS 'Unique user email (lowercased)';
COMMENT ON COLUMN public.users.password IS 'Bcrypt hashed password (never exposed or logged)';
COMMENT ON COLUMN public.users.role IS 'User account role: customer or admin';
COMMENT ON COLUMN public.users."resetOtp" IS 'Hashed OTP for password reset flow';
COMMENT ON COLUMN public.users.legacy_mongo_id IS 'Previous MongoDB ObjectId string for backwards token compatibility';
